sudo: required
services:
  - docker

before_install:
  - docker build -t macnak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true macnak/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-587523470743"
  pucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
